### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libagora-core.so" not found

### ISSUE THREAD

**Issue by ArcherEmiya05** [AgoraIO/API-Examples#166]
I am receiving a crash log from `Google Pixel 3a`

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libagora-core.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at io.agora.rtc.internal.RtcEngineImpl.loadNativeLibrary(RtcEngineImpl.java:133)
       at io.agora.rtc.internal.RtcEngineImpl.initializeNativeLibs(RtcEngineImpl.java:183)
       at io.agora.rtc.RtcEngine.create(RtcEngine.java:41)
       at com.devsbitwise.masa.App.setRtcEngine(App.java:116)
       at com.devsbitwise.masa.App.lambda$onCreate$0(App.java:78)
       at com.devsbitwise.masa.App.$r8$lambda$aJq5hfU8FUE4bQLVHdrfPNSaKcw(App.java)
       at com.devsbitwise.masa.App$$InternalSyntheticLambda$0$6a962a8aab386811e58522edb5c22ecaf8c81020c05aacd154b59c1cf0d68747$0.onSuccess(App.java:4)
       at com.google.android.gms.tasks.zzm.run(zzm.java:1)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

However I never encountered this error before. This issue is more likely from app review device since Pixel products is not available in our country. I do not know if they are using virtual or real device. Any solution?

**Comment by yoreland** [comment]
Can you provide sdk version?
Btw, how did you integrate sdk, via JitPack or download sdk from agora.io website?

**Comment by yoreland** [comment]
If you are using 3.4.1 from Jitpack, you can try to upgrade to 3.4.1.1 or 3.4.2

**Comment by ArcherEmiya05** [comment]
> 
> 
> If you are using 3.4.1 from Jitpack, you can try to upgrade to 3.4.1.1 or 3.4.2

The version is  `3.4.2`
`com.github.agorabuilder:native-full-sdk:3.4.2`

**Comment by yoreland** [comment]
good to hear!

**Comment by krghv85** [comment]
Hi, I am facing the same issue in some devices.

I integrate sdk, via agora.io website.

 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/PR6yLDBlYPvgl4VueZs1Zw==/base.apk"],nativeLibraryDirectories=[/data/PR6yLDBlYPvgl4VueZs1Zw==/lib/arm, /data/app/-PR6yLDBlYPvgl4VueZs1Zw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libagora-core.so"

Please help me.

**Comment by Lockincreate** [comment]
Hey
