### ISSUE TITLE
ScreenCapture: Draw frame failed, ignore

### ISSUE THREAD

**Issue by arvinho** [AgoraIO/API-Examples#185]
E/ScreenCapture: Draw frame failed, ignore
D/ScreenSharingService: onFrameAvailable ImgTexFrame{mFormat=ImgTexFormat{mColorFormat=3, mWidth=1080, mHeight=2259}, mTextureId=1, mTexMatrix=[1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0]} 38288815
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void io.agora.rtc.mediaio.IVideoFrameConsumer.consumeTextureFrame(int, int, int, int, int, long, float[])' on a null object reference
        at io.agora.rtc.ss.impl.ScreenSharingService$2.onFrameAvailable(ScreenSharingService.java:95)
        at io.agora.rtc.ss.impl.ScreenSharingService$2.onFrameAvailable(ScreenSharingService.java:81)
        at io.agora.rtc.ss.gles.SrcConnector.onFrameAvailable(SrcConnector.java:40)
        at io.agora.rtc.ss.impl.ScreenCapture$2.onDrawFrame(ScreenCapture.java:314)
        at io.agora.rtc.ss.gles.GLRender.drawFrame(GLRender.java:313)
        at io.agora.rtc.ss.gles.GLRender.access$300(GLRender.java:23)
        at io.agora.rtc.ss.gles.GLRender$5.handleMessage(GLRender.java:396)
        at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by yoreland** [comment]
Seems can reproduce it locally, btw, besides screen sharing, did you get other example working?

**Comment by arvinho** [comment]
sure，the example of playing local video does not work either

**Comment by arvinho** [comment]
The screen sharing operation is also available in the example of playing local video

**Comment by yoreland** [comment]
Local video demo need manually copy video resources. For ScreenShare demo.
